---
# This is a sample database file for the DataMapper ORM
:development: &defaults
  :adapter: postgresql
  :database: nasfulia
  :username: postgres
  :password:
  :host: localhost

:test:
  <<: *defaults
  :database: sample_test

:production:
  <<: *defaults
  :database: nasfulia
